config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get "angular-items", to: "portfolios#angular"
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Blog", blogs_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
    </div>

    <% if current_user.is_a?(GuestUser) %>
        <%= link_to "Register", new_user_registration_path, method: :get %>
        <%= link_to "Login", new_user_session_path, method: :get %>
    <% else %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>

    <%= yield %>

    <% if session[:source] %>
        <p>Thank you for visiting me from <%= session[:source] %></p>
    <% end %>

    <p>
      <%= copyright_generator %>
    </p>
  </body>
</html>